[package]
name = "jd_server"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"

[lib]
name = "jd_server"
path = "src/lib/mod.rs"

[dependencies]
stratum-common = { path = "../../common" }
async-channel = "1.5.1"
binary_sv2 = { version = "^0.1.6", path = "../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { version = "^0.1.2", path = "../../utils/buffer" }
codec_sv2 = { version = "*", path = "../../protocols/v2/codec-sv2", features = ["noise_sv2"] }
const_sv2 = { version = "^0.1.2", path = "../../protocols/v2/const-sv2" }
jsonrpc = { version = "^0.16.0", path = "vendored/rust-jsonrpc"}
network_helpers = { version = "0.1", path = "../../utils/network-helpers", features = ["with_tokio"] }
noise_sv2 = { version = "*", path = "../../protocols/v2/noise-sv2" }
rand = "0.8.4"
roles_logic_sv2 = { version = "^0.1.0", path = "../../protocols/v2/roles-logic-sv2" }
tokio = { version = "1", features = ["full"] }
toml = { version = "*", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
async-recursion = "1.0.0"
error_handling = { version = "0.1", path = "../../utils/error-handling" }
nohash-hasher = "0.2.0"
serde_json = { version = "1.0", default-features = false, features = ["alloc","raw_value"] }
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
hashbrown = { version = "0.11", default-features = false, features = ["ahash", "serde"] }
key-utils = { version = "^1.0.0", path = "../../utils/key-utils" }
secp256k1 = { version = "0.28.2", default-features = false, features =["alloc","rand","rand-std"] }
siphasher = "1"
hex = "0.4.3"
base64 = "0.21.5"
hyper = { version = "1.1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1"
